[package]
name = "oxr-client"
version = "0.1.0"
authors = ["korejan <64199710+korejan@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxr_common = { path = "../common" }
